version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pyr-sh/concourse-ssh-resource
    docker:
      - image: circleci/golang:1.9
      - image: quay.io/pyr-sh/alpine-ssh:v1.1.0
    steps:
      - checkout
      - run: bash .circleci/codecov.sh
